class StringBusca:

    def __init__(self):
        self.n_gramas_contra_negros = ["atendido por cotista",
                                       "cabelo ruim",
                                       "cotas raciais",
                                       "cotista desgraçado",
                                       "esse preto crl",
                                       "filme cotista",
                                       "gente negra",
                                       "gente preta",
                                       "lugar de negra",
                                       "lugar de negras",
                                       "lugar de negro",
                                       "lugar de negros",
                                       "lugar de preta",
                                       "lugar de pretas",
                                       "lugar de preto",
                                       "lugar de pretos",
                                       "merece mulher negra",
                                       "merece mulher preta",
                                       "não gosto de negro",
                                       "não gosto de negros",
                                       "não gosto de pretos",
                                       "não gosto de preto",
                                       "nega macaca",
                                       "nega",
                                       "nego macaco",
                                       "nego",
                                       "negra banana",
                                       "negra cotista",
                                       "negra feia",
                                       "negra imunda",
                                       "negra macaca",
                                       "negra vitima",
                                       "negra vitimismo",
                                       "negras cotista",
                                       "negras macaca",
                                       "negro banana",
                                       "negro cotista",
                                       "negro feio",
                                       "negro imundo",
                                       "negro macaco",
                                       "negro merece",
                                       "negro vitima",
                                       "negro vitimismo",
                                       "negros cotistas",
                                       "negros macacos",
                                       "odeio negro",
                                       "odeio negros",
                                       "odeio pretos",
                                       "oscar cotista",
                                       "por que negro",
                                       "por que preto",
                                       "povo negro",
                                       "povo preto",
                                       "pq preto",
                                       "pq negro",
                                       "preta banana",
                                       "preta cotista",
                                       "preta feia",
                                       "preta imunda",
                                       "preta macaca",
                                       "pretas cotistas",
                                       "pretas macacas",
                                       "preto banana",
                                       "preto cotista",
                                       "preto fedido",
                                       "preto feio",
                                       "preto imundo",
                                       "preto macaco",
                                       "preto merece",
                                       "pretos cotistas",
                                       "pretos macacos",
                                       "racismo",
                                       "racista",
                                       "racistas",
                                       "só podia ser negro",
                                       "só podia ser preto"]

        self.n_gramas_contra_mulheres = ["depois reclama assédio carnaval",
                                         "depois reclama assédio",
                                         "essa cachorra",
                                         "essa puta",
                                         "essa vadia",
                                         "essa vagabunda",
                                         "estuprada",
                                         "estuprei",
                                         "estupro",
                                         "falta de rola",
                                         "fecha as pernas",
                                         "feminazi",
                                         "feminista",
                                         "feministas",
                                         "lixo feminista",
                                         "lugar de mulher",
                                         "mal comida",
                                         "merece ser estuprada",
                                         "mulher aborto",
                                         "mulher apanha homem",
                                         "mulher cachorra",
                                         "mulher é tudo",
                                         "mulher lavar uns pratos",
                                         "mulher merece porrada",
                                         "mulher merece tiro",
                                         "mulher piranha",
                                         "mulher puta",
                                         "mulher que está pedindo",
                                         "mulher que ta pedindo",
                                         "mulher que",
                                         "mulher vadia",
                                         "mulher vagabunda",
                                         "mulher varrer uma casa",
                                         "nessa vagabunda",
                                         "respeita as mina",
                                         "respeitaasmina",
                                         "respeite as mina",
                                         "sapatão feminista"]